### ISSUE TITLE
Cannot parse non-Standard Dateformat

### ISSUE THREAD

**Issue by renoth** [MrAddon/jgantt#1]
We use the following Dateformat in our organisation:
```
dd.MM.yyyy (Standard German Format) 
```
which cannot be parsed by this addon and thus the initialisation fails.

**Comment by rpelaez** [comment]
Hello, only few formats are accepted, but you always can use Scriptrunner to format the Dates in script fields. Here the new documentation: https://mraddon.blog/2019/12/26/kanban-gantt-for-jira-documentation-with-adaptavist-scriptrunner/
Best regards

**Comment by rpelaez** [comment]
Hello renoth, please try with the new version
